// ============================================================================
//   ТЕКСТЫ РЕДАКТОРА ПРОЕКТОВ.
//
//   Лежат отдельно от settings.ts специально: этот файл импортирует только
//   сам редактор, а он подключается лишь при локальном запуске (npm run dev).
//   Поэтому в файл, который выкладывается на сайт, эти строки не попадают —
//   по ним нельзя догадаться, что редактор вообще существует.
// ============================================================================

import type { Lang } from "../settings";

export const ED = {
  ru: {
    ed_title:      "Редактор проектов",
    ed_open:       "Редактор проектов",
    ed_new:        "Новый проект",
    ed_delete:     "Удалить",
    ed_confirmDel: "Удалить проект? Это действие не отменить.",
    ed_export:     "Скачать projects.json",
    ed_copy:       "Скопировать код для settings.ts",
    ed_copied:     "Скопировано в буфер обмена",
    ed_reset:      "Сбросить к settings.ts",
    ed_confirmRes: "Стереть все локальные правки и вернуть проекты из settings.ts?",
    ed_empty:      "Проектов пока нет. Нажми «Новый проект».",
    ed_dropHint:   "Перетащи файл сюда или нажми Ctrl+V, чтобы вставить скриншот",
    ed_pickFile:   "Выбрать файл",
    ed_fields:     "Основное",
    ed_shots:      "Скриншоты",
    ed_team:       "Команда",
    ed_addShot:    "Добавить скриншот",
    ed_addMember:  "Добавить участника",
    ed_remove:     "Убрать",
    ed_up:         "Выше",
    ed_down:       "Ниже",
    ed_localNote:  "Правки сохраняются в этом браузере сразу. Чтобы они появились на сайте у всех — нажми «Скопировать код для settings.ts» и вставь его в src/settings.ts вместо блока PROJECTS, затем закоммить.",
    ed_lock:       "Закрыть редактор",
    ed_projects:   "Проекты",
    ed_f_id:       "ID (латиницей, без пробелов)",
    ed_f_num:      "Номер (01, 02 …)",
    ed_f_year:     "Год",
    ed_f_engine:   "Движок",
    ed_f_status:   "Стадия проекта",
    ed_f_tags:     "Теги (через запятую)",
    ed_f_cover:    "Обложка карточки",
    ed_f_title:    "Название",
    ed_f_subtitle: "Подзаголовок",
    ed_f_desc:     "Описание",
    ed_f_myRole:   "Моя роль",
    ed_f_linkUrl:  "Ссылка на игру (пусто -> кнопка скрыта)",
    ed_f_linkLabel:"Надпись на кнопке",
    ed_f_caption:  "Подпись",
    ed_f_src:      "Ссылка на картинку",
    ed_f_name:     "Имя",
    ed_f_role:     "Должность",
    ed_f_avatar:   "Аватарка (пусто -> не показывается)",
    ed_f_email:    "Почта (пусто -> кнопка скрыта)",
    ed_statusNone: "Не указана",
    ed_newProject: "Новый проект",
    ed_publish:     "Опубликовать на сайт",
    ed_publishing:  "Публикую…",
    ed_token:       "Токен GitHub",
    ed_tokenSaved:  "Токен сохранён в этом браузере",
    ed_tokenSet:    "Сохранить токен",
    ed_tokenClear:  "Удалить токен",
    ed_tokenHint:   "Нужен один раз. GitHub -> Settings -> Developer settings -> Personal access tokens -> Fine-grained tokens. Доступ: только этот репозиторий, права Contents: Read and write. Токен хранится только в твоём браузере.",
    ed_openActions: "Посмотреть сборку",
    ed_publishNote: "«Опубликовать» сохраняет проекты в репозиторий и запускает пересборку сайта. Через 1-2 минуты изменения увидят все.",
  },
  en: {
    ed_title:      "Project editor",
    ed_open:       "Project editor",
    ed_new:        "New project",
    ed_delete:     "Delete",
    ed_confirmDel: "Delete this project? This cannot be undone.",
    ed_export:     "Download projects.json",
    ed_copy:       "Copy code for settings.ts",
    ed_copied:     "Copied to clipboard",
    ed_reset:      "Reset to settings.ts",
    ed_confirmRes: "Discard all local edits and restore projects from settings.ts?",
    ed_empty:      "No projects yet. Click “New project”.",
    ed_dropHint:   "Drop a file here or press Ctrl+V to paste a screenshot",
    ed_pickFile:   "Choose file",
    ed_fields:     "Main",
    ed_shots:      "Screenshots",
    ed_team:       "Team",
    ed_addShot:    "Add screenshot",
    ed_addMember:  "Add member",
    ed_remove:     "Remove",
    ed_up:         "Up",
    ed_down:       "Down",
    ed_localNote:  "Edits are saved in this browser instantly. To publish them for everyone, click “Copy code for settings.ts”, paste it into src/settings.ts over the PROJECTS block and commit.",
    ed_lock:       "Close editor",
    ed_projects:   "Projects",
    ed_f_id:       "ID (latin, no spaces)",
    ed_f_num:      "Number (01, 02 …)",
    ed_f_year:     "Year",
    ed_f_engine:   "Engine",
    ed_f_status:   "Project stage",
    ed_f_tags:     "Tags (comma separated)",
    ed_f_cover:    "Card cover",
    ed_f_title:    "Title",
    ed_f_subtitle: "Subtitle",
    ed_f_desc:     "Description",
    ed_f_myRole:   "My role",
    ed_f_linkUrl:  "Game link (empty -> button hidden)",
    ed_f_linkLabel:"Button label",
    ed_f_caption:  "Caption",
    ed_f_src:      "Image URL",
    ed_f_name:     "Name",
    ed_f_role:     "Role",
    ed_f_avatar:   "Avatar (empty -> hidden)",
    ed_f_email:    "Email (empty -> button hidden)",
    ed_statusNone: "Not set",
    ed_newProject: "New project",
    ed_publish:     "Publish to site",
    ed_publishing:  "Publishing…",
    ed_token:       "GitHub token",
    ed_tokenSaved:  "Token saved in this browser",
    ed_tokenSet:    "Save token",
    ed_tokenClear:  "Delete token",
    ed_tokenHint:   "Needed once. GitHub -> Settings -> Developer settings -> Personal access tokens -> Fine-grained tokens. Access: this repository only, Contents: Read and write. The token stays in your browser.",
    ed_openActions: "View the build",
    ed_publishNote: "Publish saves the projects to the repository and triggers a rebuild. Everyone sees the changes in 1-2 minutes.",
  },
} satisfies Record<Lang, Record<string, string>>;

export type EdText = (typeof ED)["ru"];
